# Generated by Django 3.2.5 on 2021-07-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210704_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterIndexTogether(
            name='maininform',
            index_together=set(),
        ),
    ]
